DECLARE @count INT;
SELECT @count=COUNT(*)
FROM STATION;
SELECT CAST(
CASE 
	WHEN @count%2=0 
	THEN 
		(
			(SELECT TOP 1 LAT_N FROM (SELECT TOP 50 PERCENT LAT_N FROM STATION ORDER BY LAT_N) A ORDER BY LAT_N DESC) +
			(SELECT TOP 1 LAT_N FROM (SELECT TOP 50 PERCENT LAT_N FROM STATION ORDER BY LAT_N DESC) A ORDER BY LAT_N)
		)/2 
	ELSE 
		(SELECT TOP 1 LAT_N FROM (SELECT TOP 50 PERCENT LAT_N FROM STATION ORDER BY LAT_N) A ORDER BY LAT_N DESC)
END

AS DECIMAL(10,4))