CREATE TABLE [dbo].[COUNTRY]
(
	[CODE] VARCHAR(3),
	[NAME] VARCHAR(44),
	[CONTINENT] VARCHAR(13),
	[REGION] VARCHAR(25),
	[SURFACEAREA] INT,
	[INDEPYEAR] VARCHAR(5),
	[POPULATION] INT,
	[LIFEEXPECTANCY] VARCHAR(4),
	[GNP] INT,
	[GNPOLD] VARCHAR(9),
	[LOCALNAME] VARCHAR(44),
	[GOVERNMENTFORM] VARCHAR(44),
	[HEADOFSTATE] VARCHAR(32),
	[CAPITAL] VARCHAR(4),
	[CODE2] VARCHAR(2)
)
